monthly_to_daily <- function(date,
                             value,
                             what = "cumulative",
                             format="myd"){

  # Check arguments and parse the dates with lubridate's functions

  if(!is.numeric(value)){
    stop("monthly values must be numeric.")
  }
# print(pmatch(what,"cumulative"))
  if(!(isTRUE(as.logical(pmatch(what,"cumulative")))|isTRUE(as.logical(pmatch(what, "mean"))))){
    stop("what argument must indicate whether your values are means or monthly cumulated precipitations, thus it has to partially match either 'mean' or 'cumulative'.")
  }
  if(!is.character(date)){
    if(is.factor(date)){
      date <- as.character(date)
    }
    else if(!lubridate::is.instant(date)){
      stop("the dates you inputted are neither a character (or a factor coercicible to character) nor an instant (see lubridate's vignette). We cannot deal with other types than these")
    }
  }

  if(!lubridate::is.instant(date)){
    if(isTRUE(pmatch(format, "ymd"))){
      date <- try(lubridate::ymd(date, truncated = 1))
      if(inherits(date, "try-error")){
        stop("The format you indicated is apparently wrong, and the dates failed to be parsed.")
      }
    }
    else if(isTRUE(pmatch(format, "myd"))){
      date <- try(lubridate::myd(date, truncated = 1))
      if(inherits(date, "try-error")){
        stop("The format you indicated is apparently wrong, and the dates failed to be parsed.")
      }
    }
    else stop("The format argument (indicating the format of the inputted dates) must partially match one of the following: 'ymd' (year-month-day) or 'myd' (month-year-day)")

    if(any(is.na(date))){
      stop("The format you indicated might be wrong: NAs were generated by parsing the dates into POSIXct objects.")
    }
  }

  # Obtain all the dates within each month
  d <- data.frame(Date = date, Value = value)
  if(isTRUE(as.logical(pmatch(what,"mean")))){
    data <- do.call("rbind", lapply(1:nrow(d), function(i)
      data.frame(Date = seq(d$Date[i],
                            (seq(d$Date[i],length=2,by="months") - 1)[2], by = "1 days"),
                 value = d$Value[i])))
  }
  else if(isTRUE(as.logical(pmatch(what,"cumulative")))){
    data <- do.call("rbind", lapply(1:nrow(d), function(i){
      Date <- seq(d$Date[i],
                  (seq(d$Date[i],length=2,by="months") - 1)[2], by = "1 days")
      return(data.frame(Date = Date,
                 value = d$Value[i]/length(Date)))
    }))
  }
  return(data)
}

